### ISSUE TITLE
error module settings not found

### ISSUE THREAD

**Issue by javiermarcon** [gaccardo/buxfer_api#2]
Hello,

When I try to run buxfer -h it gives me the error that the settings module is not installed. Which package am  missing to install?

Traceback (most recent call last):
  File "buxfer", line 5, in <module>
    from buxfer_commands.show_balance import ShowBalance
  File "/home/javier/proyectos/finanzas/buxfer_api/buxfer_commands/show_balance.py", line 3, in <module>
    import settings
ImportError: No module named settings

I have already installed the the packages listed in requirements file, but I can't figure out which one is missing.

Thanks,

Javier.

**Comment by javiermarcon** [comment]
Sorry I didnt realized that I had to cop the settings-sample.py into settings.py and fill the vars.

**Comment by gaccardo** [comment]
@javiermarcon hi. Yeah sorry, this is a very old piece of code and to be completely honest, I dropped it soon after i started. As you can see the documentation is virtually unexistent. Anyway let me know if I can help you in anyway with this.
